#!/bin/sh
set -e

if [ "$1" = "--json" ]; then
    # Output JSON format, rename 'number' field to 'id'
    gh pr list --json number,state,title,isDraft,createdAt,updatedAt,url -s all -L 1000 | jq 'map(.id = .number | del(.number))'
else
    # Output tab-separated format with header
    echo -e "ID\tstate\ttitle\tisDraft\tcreatedAt\tupdatedAt\turl"
    gh pr list --json number,state,title,isDraft,createdAt,updatedAt,url --template '{{range .}}{{.number}}	{{.state}}	{{.title}}	{{.isDraft}}	{{.createdAt}}	{{.updatedAt}}	{{.url}}
{{end}}' -s all -L 1000
fi
