#!/bin/sh
set -e

WEB_APP_URL="https://script.google.com/macros/s/AKfycbyR2-zTNmdYDZmwBMc8WFSiC5oBopnJd5rNIC406t0kGDjm_1z_UuTQ9-6M9i9k558/exec"

if [ $# -eq 0 ] || [[ "$1" != "sync" && "$1" != "get" ]]; then
    echo "Usage: $0 <sync|get>"
    exit 1
fi

if [ "$1" = "sync" ]; then
    ./list-prs --json | curl -L -H "Content-Type: application/json" -d @- "$WEB_APP_URL"
else
    curl -L "$WEB_APP_URL"
fi
